# Generated by Django 4.2.6 on 2023-11-07 03:15

import app.models.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
            bases=(app.models.mixins.TimeStampedMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providers",
                        to="app.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
            },
            bases=(app.models.mixins.TimeStampedMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProviderOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("url", models.URLField()),
                (
                    "contacts",
                    models.ManyToManyField(through="app.Provider", to="app.contact"),
                ),
            ],
            options={
                "verbose_name": "Provider Organization",
                "verbose_name_plural": "Provider Organizations",
            },
            bases=(app.models.mixins.TimeStampedMixin, models.Model),
        ),
        migrations.AddField(
            model_name="provider",
            name="provider_organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.providerorganization",
            ),
        ),
    ]
